// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN_M2aoQzdbZBBb9NuwHV-gFc1oud2l-0',
    appId: '1:471500357884:web:e58b251dd367759d595779',
    messagingSenderId: '471500357884',
    projectId: 'project-zero-91d24',
    authDomain: 'project-zero-91d24.firebaseapp.com',
    storageBucket: 'project-zero-91d24.firebasestorage.app',
    measurementId: 'G-YHXG4XFES4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGRQP9PJ39EdL0iWRiK72Lt3_8Fz_GNbY',
    appId: '1:471500357884:android:21e9120b95f7e8bf595779',
    messagingSenderId: '471500357884',
    projectId: 'project-zero-91d24',
    storageBucket: 'project-zero-91d24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmBBlFv91NkDyrAT8bZnIq6iW7X-55Kgc',
    appId: '1:471500357884:ios:c9588cfb8dba14ad595779',
    messagingSenderId: '471500357884',
    projectId: 'project-zero-91d24',
    storageBucket: 'project-zero-91d24.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmBBlFv91NkDyrAT8bZnIq6iW7X-55Kgc',
    appId: '1:471500357884:ios:c9588cfb8dba14ad595779',
    messagingSenderId: '471500357884',
    projectId: 'project-zero-91d24',
    storageBucket: 'project-zero-91d24.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN_M2aoQzdbZBBb9NuwHV-gFc1oud2l-0',
    appId: '1:471500357884:web:fb0887fb9c173592595779',
    messagingSenderId: '471500357884',
    projectId: 'project-zero-91d24',
    authDomain: 'project-zero-91d24.firebaseapp.com',
    storageBucket: 'project-zero-91d24.firebasestorage.app',
    measurementId: 'G-2WVC7YES6X',
  );
}
